AllCops:
  TargetRubyVersion: 2.7

Layout:
  Severity: refactor

Naming:
  Severity: refactor

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Lint/Debugger:
  Enabled: false
